title: OfferDesk
email: info@offerdesk.com
description: >-
  OfferDesk website.
baseurl: ""
url: "https://offerdesk.github.io"

# GitHub Pages safe plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
theme: minima
markdown: kramdown
exclude:
  - node_modules
  - resources
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .prettierrc
  - Gemfile
  - Gemfile.lock
source: docs
