title: OfferDesk
email: info@offerdesk.com
description: >-
  OfferDesk helpt servicebedrijven van offerte tot uitvoering: offertes, marges,
  goedkeuring, materialen en winst in één platform.
default_lang: nl
google_analytics_id: G-XMLKF7JVEX
mailerlite:
  action: "https://assets.mailerlite.com/jsonp/2670655/forms/199973805230130365/subscribe"
baseurl: ""
url: "https://offerdesk.nl"

# GitHub Pages safe plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
theme: minima
markdown: kramdown
exclude:
  - node_modules
  - resources
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .prettierrc
  - Gemfile
  - Gemfile.lock
source: docs
